[default]
src = 'tests/foundry'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    'ds-test/=lib/ds-test/src/', 
    'forge-std/=lib/forge-std/src/',
    'OpenZeppelin/openzeppelin-contracts@4.7.3/=lib/openzeppelin-contracts/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config